name: "✨ Feature Request"
description: "Request a new feature or improvement"
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: input
    id: summary
    attributes:
      label: "Short Summary"
      placeholder: "e.g. Add export to PDF button"
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: "Describe the Feature"
      description: "Why is this feature needed? How should it work?"
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: "Priority"
      options:
        - Low
        - Medium
        - High
